export { default as AvatarsList } from './AvatarsList'
export { default as CustomChart } from './CustomChart'
export { default as CustomTable } from './CustomTable'
export { default as FormComponent } from './FormComponent'
export { default as Header } from './Header'
export { default as MenuPage } from './MenuPage'
export { default as SalesInteligence } from './SalesInteligence'
export * from './BannerImage'
export * from './CardComponent'
export * from './Logo'
export * from './StyledButton'
export * from './StyledInput'
export * from './Typographies'
export * from './ImgCartoonOpticaAndTech'
export * from './ImgMenuTechAndOptica'
export * from './SmartSelling'
export * from './ResumePage'
